export const ADD_FRIEND = 'ADD_FRIEND'
export const NEW_GAME = 'NEW_GAME'
export const LABEL_PLACED = 'LABEL_PLACED'
export const GET_USER = 'GET_USER'
export const SET_STORAGE_BOX = 'SET_STORAGE_BOX'